// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAQX7aTaamrQWCx99lo0ieEIRpDq3RrxU',
    appId: '1:405442372394:web:3e2f37c256a6d55be1f453',
    messagingSenderId: '405442372394',
    projectId: 'oto-asistanim-2025',
    authDomain: 'oto-asistanim-2025.firebaseapp.com',
    storageBucket: 'oto-asistanim-2025.firebasestorage.app',
    measurementId: 'G-T6KB08LP1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLlhd751lptZ-Iverde3O74j9r50YJZY4',
    appId: '1:405442372394:android:009c2842e044dccae1f453',
    messagingSenderId: '405442372394',
    projectId: 'oto-asistanim-2025',
    storageBucket: 'oto-asistanim-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOck6WiTaUOBl7NoPMUGeqwxHD3Ed052k',
    appId: '1:405442372394:ios:e7db4e1e3a9f318fe1f453',
    messagingSenderId: '405442372394',
    projectId: 'oto-asistanim-2025',
    storageBucket: 'oto-asistanim-2025.firebasestorage.app',
    iosBundleId: 'com.example.otoAsistan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOck6WiTaUOBl7NoPMUGeqwxHD3Ed052k',
    appId: '1:405442372394:ios:e7db4e1e3a9f318fe1f453',
    messagingSenderId: '405442372394',
    projectId: 'oto-asistanim-2025',
    storageBucket: 'oto-asistanim-2025.firebasestorage.app',
    iosBundleId: 'com.example.otoAsistan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAQX7aTaamrQWCx99lo0ieEIRpDq3RrxU',
    appId: '1:405442372394:web:0bcdc3741ce6db41e1f453',
    messagingSenderId: '405442372394',
    projectId: 'oto-asistanim-2025',
    authDomain: 'oto-asistanim-2025.firebaseapp.com',
    storageBucket: 'oto-asistanim-2025.firebasestorage.app',
    measurementId: 'G-H1N9GQHWHS',
  );

}